In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 100)
pd.set_option('max_colwidth', 70)

In [3]:
df_data = pd.read_csv("owid-covid-data.csv")

In [4]:
df_data.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed',
       'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million',
       'reproduction_rate', 'icu_patients', 'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions', 'weekly_icu_admissions_per_million',
       'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed',
       'new_tests_smoothed_per_thousand', 'positive_rate', 'tests_per_case', 'tests_units',
       'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred',
       'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
       'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred',
       'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities',
       'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality',
       'excess_mortality_cumulative_per_million'],
      dtype='object')

In [5]:
df_data.shape

(191376, 67)

In [6]:
# In order to understand the available data we use the column description csv priovided
df_desc = pd.read_csv("owid-covid-codebook.csv", index_col = 'column').description
df_desc

column
iso_code                                                            ISO 3166-1 alpha-3 â€“ three-letter country codes
continent                                                                    Continent of the geographical location
location                                                                                      Geographical location
date                                                                                            Date of observation
total_cases                                   Total confirmed cases of COVID-19. Counts can include probable cas...
new_cases                                     New confirmed cases of COVID-19. Counts can include probable cases...
new_cases_smoothed                            New confirmed cases of COVID-19 (7-day smoothed). Counts can inclu...
total_deaths                                  Total deaths attributed to COVID-19. Counts can include probable d...
new_deaths                                    New deaths attributed to COVID-19. Counts can include probable dea...
new_deaths_smoothed                           New deaths attributed to COVID-19 (7-day smoothed). Counts can inc...
total_cases_per_million                       Total confirmed cases of COVID-19 per 1,000,000 people. Counts can...
new_cases_per_million                         New confirmed cases of COVID-19 per 1,000,000 people. Counts can i...
new_cases_smoothed_per_million                New confirmed cases of COVID-19 (7-day smoothed) per 1,000,000 peo...
total_deaths_per_million                      Total deaths attributed to COVID-19 per 1,000,000 people. Counts c...
new_deaths_per_million                        New deaths attributed to COVID-19 per 1,000,000 people. Counts can...
new_deaths_smoothed_per_million               New deaths attributed to COVID-19 (7-day smoothed) per 1,000,000 p...
reproduction_rate                             Real-time estimate of the effective reproduction rate (R) of COVID...
icu_patients                                  Number of COVID-19 patients in intensive care units (ICUs) on a gi...
icu_patients_per_million                      Number of COVID-19 patients in intensive care units (ICUs) on a gi...
hosp_patients                                                Number of COVID-19 patients in hospital on a given day
hosp_patients_per_million                     Number of COVID-19 patients in hospital on a given day per 1,000,0...
weekly_icu_admissions                         Number of COVID-19 patients newly admitted to intensive care units...
weekly_icu_admissions_per_million             Number of COVID-19 patients newly admitted to intensive care units...
weekly_hosp_admissions                        Number of COVID-19 patients newly admitted to hospitals in a given...
weekly_hosp_admissions_per_million            Number of COVID-19 patients newly admitted to hospitals in a given...
total_tests                                                                                Total tests for COVID-19
new_tests                                             New tests for COVID-19 (only calculated for consecutive days)
total_tests_per_thousand                                                  Total tests for COVID-19 per 1,000 people
new_tests_per_thousand                                                      New tests for COVID-19 per 1,000 people
new_tests_smoothed                            New tests for COVID-19 (7-day smoothed). For countries that don't ...
new_tests_smoothed_per_thousand                            New tests for COVID-19 (7-day smoothed) per 1,000 people
positive_rate                                 The share of COVID-19 tests that are positive, given as a rolling ...
tests_per_case                                Tests conducted per new confirmed case of COVID-19, given as a rol...
tests_units                                                   Units used by the location to report its testing data
total_vaccinations                                          Total number of COVID-19 vaccination doses administered
people_vaccinated                                     Total number of people who received at least one vaccine dose
people_fully_vaccinated                       Total number of people who received all doses prescribed by the in...
total_boosters                                Total number of COVID-19 vaccination booster doses administered (d...
new_vaccinations                              New COVID-19 vaccination doses administered (only calculated for c...
new_vaccinations_smoothed                     New COVID-19 vaccination doses administered (7-day smoothed). For ...
total_vaccinations_per_hundred                Total number of COVID-19 vaccination doses administered per 100 pe...
people_vaccinated_per_hundred                 Total number of people who received at least one vaccine dose per ...
people_fully_vaccinated_per_hundred           Total number of people who received all doses prescribed by the in...
total_boosters_per_hundred                    Total number of COVID-19 vaccination booster doses administered pe...
new_vaccinations_smoothed_per_million         New COVID-19 vaccination doses administered (7-day smoothed) per 1...
new_people_vaccinated_smoothed                Daily number of people receiving their first vaccine dose (7-day s...
new_people_vaccinated_smoothed_per_hundred    Daily number of people receiving their first vaccine dose (7-day s...
stringency_index                              Government Response Stringency Index: composite measure based on 9...
population                                    Population (latest available values). See https://github.com/owid/...
population_density                            Number of people divided by land area, measured in square kilomete...
median_age                                                     Median age of the population, UN projection for 2020
aged_65_older                                 Share of the population that is 65 years and older, most recent ye...
aged_70_older                                            Share of the population that is 70 years and older in 2015
gdp_per_capita                                Gross domestic product at purchasing power parity (constant 2011 i...
extreme_poverty                               Share of the population living in extreme poverty, most recent yea...
cardiovasc_death_rate                         Death rate from cardiovascular disease in 2017 (annual number of d...
diabetes_prevalence                                     Diabetes prevalence (% of population aged 20 to 79) in 2017
female_smokers                                                 Share of women who smoke, most recent year available
male_smokers                                                     Share of men who smoke, most recent year available
handwashing_facilities                        Share of the population with basic handwashing facilities on premi...
hospital_beds_per_thousand                    Hospital beds per 1,000 people, most recent year available since 2010
life_expectancy                                                                    Life expectancy at birth in 2019
human_development_index                       A composite index measuring average achievement in three basic dim...
excess_mortality                              Percentage difference between the reported number of weekly or mon...
excess_mortality_cumulative                   Percentage difference between the cumulative number of deaths sinc...
excess_mortality_cumulative_absolute          Cumulative difference between the reported number of deaths since ...
excess_mortality_cumulative_per_million       Cumulative difference between the reported number of deaths since ...
Name: description, dtype: object

In [7]:
df_desc["hospital_beds_per_thousand"]

'Hospital beds per 1,000 people, most recent year available since 2010'

In [8]:
df_data.head(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,0.126,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,0.126,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,0.126,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,0.126,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,0.126,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
5,AFG,Asia,Afghanistan,2020-02-29,5.0,0.0,0.714,NaN,NaN,NaN,0.126,0.000,0.018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
6,AFG,Asia,Afghanistan,2020-03-01,5.0,0.0,0.714,NaN,NaN,NaN,0.126,0.000,0.018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.78,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
7,AFG,Asia,Afghanistan,2020-03-02,5.0,0.0,0.000,NaN,NaN,NaN,0.126,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.78,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
8,AFG,Asia,Afghanistan,2020-03-03,5.0,0.0,0.000,NaN,NaN,NaN,0.126,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.78,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
9,AFG,Asia,Afghanistan,2020-03-04,5.0,0.0,0.000,NaN,NaN,NaN,0.126,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.78,39835428.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [9]:
df_data["location"].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Asia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'European Union',
       'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France',
       'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam',
       'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'High income', 'Honduras', 'Hong Kong', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'International', 'Iran', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low income',
       'Lower middle income', 'Luxembourg', 'Macao', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America', 'North Korea', 'North Macedonia',
       'Northern Cyprus', 'Northern Mariana Islands', 'Norway', 'Oceania',
       'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn',
       'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia',
       'Rwanda', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tokelau',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'United States Virgin Islands',
       'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Vatican', 'Venezuela', 'Vietnam', 'Wallis and Futuna',
       'Western Sahara', 'World', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

# 1.2 Examining the Quality of the Data

We want to check the quality of the data, e.g. missing values in order to have a good view of how to proceed for the analysis. <br> We check not only the the total missing values, but also the distribution of them throughout the data collection period, by creating a Dataframe with the sum of missing values of each year.

In [10]:
df_data.isnull().sum()

iso_code                                           0
continent                                      11126
location                                           0
date                                               0
total_cases                                     7542
new_cases                                       7755
new_cases_smoothed                              8929
total_deaths                                   26008
new_deaths                                     26015
new_deaths_smoothed                            27178
total_cases_per_million                         8390
new_cases_per_million                           8603
new_cases_smoothed_per_million                  9772
total_deaths_per_million                       26843
new_deaths_per_million                         26850
new_deaths_smoothed_per_million                28008
reproduction_rate                              50666
icu_patients                                  165880
icu_patients_per_million                      165880
hosp_patients                                 164629
hosp_patients_per_million                     164629
weekly_icu_admissions                         185154
weekly_icu_admissions_per_million             185154
weekly_hosp_admissions                        178979
weekly_hosp_admissions_per_million            178979
total_tests                                   113693
new_tests                                     117368
total_tests_per_thousand                      113693
new_tests_per_thousand                        117368
new_tests_smoothed                             90061
new_tests_smoothed_per_thousand                90061
positive_rate                                  97935
tests_per_case                                 99695
tests_units                                    87297
total_vaccinations                            138988
people_vaccinated                             141467
people_fully_vaccinated                       144001
total_boosters                                166924
new_vaccinations                              148464
new_vaccinations_smoothed                      87798
total_vaccinations_per_hundred                138988
people_vaccinated_per_hundred                 141467
people_fully_vaccinated_per_hundred           144001
total_boosters_per_hundred                    166924
new_vaccinations_smoothed_per_million          87798
new_people_vaccinated_smoothed                 88885
new_people_vaccinated_smoothed_per_hundred     88885
stringency_index                               42755
population                                      1165
population_density                             20852
median_age                                     33324
aged_65_older                                  34999
aged_70_older                                  34153
gdp_per_capita                                 34171
extreme_poverty                                88751
cardiovasc_death_rate                          33684
diabetes_prevalence                            25975
female_smokers                                 72108
male_smokers                                   73743
handwashing_facilities                        113899
hospital_beds_per_thousand                     51462
life_expectancy                                12412
human_development_index                        37755
excess_mortality_cumulative_absolute          184823
excess_mortality_cumulative                   184823
excess_mortality                              184823
excess_mortality_cumulative_per_million       184823
dtype: int64

In [11]:
null_data_2020 = df_data[df_data["date"]<='2020-12-31'].isnull().sum().values
null_data_2021 = df_data[(df_data["date"]>='2021-01-01') & (df_data["date"]<='2021-12-31')].isnull().sum().values
null_data_2022 =df_data[df_data["date"]>='2022-01-01'].isnull().sum().values

df_null = pd.DataFrame(list(zip(null_data_2020,null_data_2021,null_data_2022)), columns=["2020","2021","2022"], index = df_data.columns.to_list())
df_null

                                             2020   2021   2022
iso_code                                        0      0      0
continent                                    4379   4745   2002
location                                        0      0      0
date                                            0      0      0
total_cases                                  1820   4398   1324
new_cases                                    1879   4440   1436
new_cases_smoothed                           3017   4471   1441
total_deaths                                13251  10100   2657
new_deaths                                  13114  10160   2741
new_deaths_smoothed                         14129  10254   2795
total_cases_per_million                      2149   4763   1478
new_cases_per_million                        2208   4805   1590
new_cases_smoothed_per_million               3341   4836   1595
total_deaths_per_million                    13567  10465   2811
new_deaths_per_million                      13430  10525   2895
new_deaths_smoothed_per_million             14440  10619   2949
reproduction_rate                           20799  19702  10165
icu_patients                                59535  74735  31610
icu_patients_per_million                    59535  74735  31610
hosp_patients                               58918  74123  31588
hosp_patients_per_million                   58918  74123  31588
weekly_icu_admissions                       66453  83682  35019
weekly_icu_admissions_per_million           66453  83682  35019
weekly_hosp_admissions                      64114  81006  33859
weekly_hosp_admissions_per_million          64114  81006  33859
total_tests                                 39191  50748  23754
new_tests                                   39902  52067  25399
total_tests_per_thousand                    39191  50748  23754
new_tests_per_thousand                      39902  52067  25399
new_tests_smoothed                          35509  39327  15225
new_tests_smoothed_per_thousand             35509  39327  15225
positive_rate                               38182  42913  16840
tests_per_case                              38864  43393  17438
tests_units                                 34427  38388  14482
total_vaccinations                          67734  49244  22010
people_vaccinated                           67740  50940  22787
people_fully_vaccinated                     67959  53632  22410
total_boosters                              68120  74422  24382
new_vaccinations                            67788  55839  24837
new_vaccinations_smoothed                   67665  15322   4811
total_vaccinations_per_hundred              67734  49244  22010
people_vaccinated_per_hundred               67740  50940  22787
people_fully_vaccinated_per_hundred         67959  53632  22410
total_boosters_per_hundred                  68120  74422  24382
new_vaccinations_smoothed_per_million       67665  15322   4811
new_people_vaccinated_smoothed              67697  16046   5142
new_people_vaccinated_smoothed_per_hundred  67697  16046   5142
stringency_index                            12918  19566  10271
population                                    329    682    154
population_density                           6817   9965   4070
median_age                                  10827  15936   6561
aged_65_older                               11463  16666   6870
aged_70_older                               11137  16301   6715
gdp_per_capita                              11536  16143   6492
extreme_poverty                             30706  40933  17112
cardiovasc_death_rate                       11005  15963   6716
diabetes_prevalence                          8628  12367   4980
female_smokers                              24528  33708  13872
male_smokers                                25125  34438  14180
handwashing_facilities                      40332  51805  21762
hospital_beds_per_thousand                  17197  24276   9989
life_expectancy                              4327   5782   2303
human_development_index                     12475  17994   7286
excess_mortality_cumulative_absolute        65331  83838  35654
excess_mortality_cumulative                 65331  83838  35654
excess_mortality                            65331  83838  35654
excess_mortality_cumulative_per_million     65331  83838  35654

We observe that in some Feutures correlated with vaccinations and deaths, we have more missing values in the first year of the pandemic(2020), which is  something  expected in the early stages

# 2.1 Feature Selection

As we previously saw, the data consists of 67 features. Not all of them are important for our analysis, so we need to carefully select the ones that we may find useful.The first step is to **categorize** them as following:
- **Location and Date**
- **Covid cases**
- **Vaccinations Rate**
- **Demographics**
- **Medical and Life Quality**

In [12]:
selected_cols = [
    
    # Location and Date
    "continent","location","date",
    
    # Covid cases
    "new_cases","new_cases_per_million","total_cases_per_million","new_deaths_per_million","total_deaths_per_million",
    "new_tests_per_thousand","reproduction_rate",
    
    # Vaccinations Rate
    "new_vaccinations_smoothed","people_vaccinated_per_hundred","total_boosters_per_hundred",
    
    # Demographics
    "population", "population_density","aged_65_older","aged_70_older",
    
    # Medical and Life Quality
    "handwashing_facilities","stringency_index","human_development_index","gdp_per_capita","extreme_poverty",
    "life_expectancy","hospital_beds_per_thousand"
    
]

In [13]:
df_selected_data = df_data[selected_cols].copy()
df_selected_data.head(10)

,continent,location,date,new_cases,new_cases_per_million,total_cases_per_million,new_deaths_per_million,total_deaths_per_million,new_tests_per_thousand,reproduction_rate,new_vaccinations_smoothed,people_vaccinated_per_hundred,total_boosters_per_hundred,population,population_density,aged_65_older,aged_70_older,handwashing_facilities,stringency_index,human_development_index,gdp_per_capita,extreme_poverty,life_expectancy,hospital_beds_per_thousand
0,Asia,Afghanistan,2020-02-24,5.0,0.126,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,8.33,0.511,1803.987,NaN,64.83,0.5
1,Asia,Afghanistan,2020-02-25,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,8.33,0.511,1803.987,NaN,64.83,0.5
2,Asia,Afghanistan,2020-02-26,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,8.33,0.511,1803.987,NaN,64.83,0.5
3,Asia,Afghanistan,2020-02-27,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,8.33,0.511,1803.987,NaN,64.83,0.5
4,Asia,Afghanistan,2020-02-28,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,8.33,0.511,1803.987,NaN,64.83,0.5
5,Asia,Afghanistan,2020-02-29,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,8.33,0.511,1803.987,NaN,64.83,0.5
6,Asia,Afghanistan,2020-03-01,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,27.78,0.511,1803.987,NaN,64.83,0.5
7,Asia,Afghanistan,2020-03-02,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,27.78,0.511,1803.987,NaN,64.83,0.5
8,Asia,Afghanistan,2020-03-03,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,27.78,0.511,1803.987,NaN,64.83,0.5
9,Asia,Afghanistan,2020-03-04,0.0,0.000,0.126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,27.78,0.511,1803.987,NaN,64.83,0.5

# 3. Data Cleansing

One of the first and most important steps of **Data Analysis** is examining the acquired raw data and **_"clean"_** them. The outcome of this step will provide us with clean, quility data to work with.

In [14]:
# View the data types of the selected features
df_selected_data.dtypes

continent                         object
location                          object
date                              object
new_cases                        float64
new_cases_per_million            float64
total_cases_per_million          float64
new_deaths_per_million           float64
total_deaths_per_million         float64
new_tests_per_thousand           float64
reproduction_rate                float64
new_vaccinations_smoothed        float64
people_vaccinated_per_hundred    float64
total_boosters_per_hundred       float64
population                       float64
population_density               float64
aged_65_older                    float64
aged_70_older                    float64
handwashing_facilities           float64
stringency_index                 float64
human_development_index          float64
gdp_per_capita                   float64
extreme_poverty                  float64
life_expectancy                  float64
hospital_beds_per_thousand       float64
dtype: object

## 3.1 Convert Date column to Datetime type

The first thing we see is that the **date** Feature which is stored as string. We will convert it to **Datetime** type

In [15]:
# converts date to M8[ns], which is a 'synomym' to datetime64[ns]

df_selected_data['date']=pd.to_datetime(df_selected_data["date"],format='%Y-%m-%d')
df_selected_data["date"].dtypes

dtype('<M8[ns]')

## 3.2 Dealing with NaN values

After finishing with the data types of the features we now have to deal with the **missing values** of our data. It is reasonable that not all countries have complete data, so we must deal with these issues. In the following table we see the count of our missing values.

In [16]:
df_selected_data.isna().sum()

continent                         11126
location                              0
date                                  0
new_cases                          7755
new_cases_per_million              8603
total_cases_per_million            8390
new_deaths_per_million            26850
total_deaths_per_million          26843
new_tests_per_thousand           117368
reproduction_rate                 50666
new_vaccinations_smoothed         87798
people_vaccinated_per_hundred    141467
total_boosters_per_hundred       166924
population                         1165
population_density                20852
aged_65_older                     34999
aged_70_older                     34153
handwashing_facilities           113899
stringency_index                  42755
human_development_index           37755
gdp_per_capita                    34171
extreme_poverty                   88751
life_expectancy                   12412
hospital_beds_per_thousand        51462
dtype: int64

### 3.2.1 Removing unwanted NaN values

In [17]:
'''
We observe that 11.126 rows have a missing value on the continent column.The reason is that there are data also for the entire
world, which we do not need in our analysis as it is country based.
We are going to solve this issue by removing the rows with missing values or whitespaces.
'''

# Replace whitespaces with NaN
df_selected_data.continent.replace('', pd.NA, inplace = True)

# Delete NaN values
df_selected_data.dropna(subset = ["continent"], inplace = True)

### 3.2.2 Filling NaN values with approximation data


There are also a small number of missing values in some of our depandand features like  "new_cases_per_million", "total_cases_per_million, "new_deaths_per_million", "total_deaths_per_million" . Performing interpolation in other columns with very high percentage of missing values, like "new_tests_per_thousand" or "people_vaccinated_per_hundred", may result in unreliable data that are not reflecting the reality. Also, these features are somewhat normal to have many missing values, as vaccines and tests came at a later stage of the covid outbreak.  <br><br>
This is something to be expected as not all countries provide daily data, especially the least developed ones.We need to fill those NaN values in a proper manner. One of the methods suitable to these kind of situations, where we have access to daily data, is by using the **interpolation method**. <br> <br>
Interpolation is the process of using known data values to estimate unknown data values, and on its simpliest forms is the **linear interpolation**. It is important to note that we make an approximate assumpion that the covid-19 follows a linear pattern. In the following code block we apply linear interpolation on specific columns.

In [18]:
# Sort our Dataframe by location in ascending order, and by date in Descending order, in order to property perform the
# interpolation

df_selected_data_sorted = df_selected_data.sort_values(["location", 'date'], ascending = [True, False]).copy()

df_selected_data_sorted.head(5)

,continent,location,date,new_cases,new_cases_per_million,total_cases_per_million,new_deaths_per_million,total_deaths_per_million,new_tests_per_thousand,reproduction_rate,new_vaccinations_smoothed,people_vaccinated_per_hundred,total_boosters_per_hundred,population,population_density,aged_65_older,aged_70_older,handwashing_facilities,stringency_index,human_development_index,gdp_per_capita,extreme_poverty,life_expectancy,hospital_beds_per_thousand
830,Asia,Afghanistan,2022-06-03,64.0,1.607,4533.251,0.000,193.496,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,NaN,0.511,1803.987,NaN,64.83,0.5
829,Asia,Afghanistan,2022-06-02,101.0,2.535,4531.645,0.025,193.496,NaN,NaN,NaN,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,NaN,0.511,1803.987,NaN,64.83,0.5
828,Asia,Afghanistan,2022-06-01,72.0,1.807,4529.109,0.050,193.471,NaN,NaN,5899.0,13.7,NaN,39835428.0,54.422,2.581,1.337,37.746,NaN,0.511,1803.987,NaN,64.83,0.5
827,Asia,Afghanistan,2022-05-31,88.0,2.209,4527.302,0.100,193.421,NaN,NaN,5899.0,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,NaN,0.511,1803.987,NaN,64.83,0.5
826,Asia,Afghanistan,2022-05-30,85.0,2.134,4525.093,0.000,193.320,NaN,NaN,5899.0,NaN,NaN,39835428.0,54.422,2.581,1.337,37.746,NaN,0.511,1803.987,NaN,64.83,0.5

In [19]:
# the Feautures that we are going to perform interpolation

interpolate_list = ['new_cases_per_million', 'total_cases_per_million',
       'new_deaths_per_million', 'total_deaths_per_million','reproduction_rate']

# We perform interpolation on both directions(forward,backward) to fill all the missing values with the linear calculation

for column in interpolate_list:
    df_selected_data_sorted[column] = df_selected_data_sorted[column].interpolate(method = "linear",limit_direction = "both")

In [20]:
df_selected_data_sorted.isnull().sum()

continent                             0
location                              0
date                                  0
new_cases                          7755
new_cases_per_million                 0
total_cases_per_million               0
new_deaths_per_million                0
total_deaths_per_million              0
new_tests_per_thousand           106242
reproduction_rate                     0
new_vaccinations_smoothed         82911
people_vaccinated_per_hundred    136649
total_boosters_per_hundred       160983
population                          317
population_density                10590
aged_65_older                     24737
aged_70_older                     23891
handwashing_facilities           103637
stringency_index                  31629
human_development_index           27493
gdp_per_capita                    23909
extreme_poverty                   78489
life_expectancy                    2150
hospital_beds_per_thousand        41200
dtype: int64

Next we are going to use the **_.descibe()_** method to view a brief summary and statistics of our selected features.

In [21]:
df_selected_data_sorted.describe().style.set_sticky(axis=0)

- **Stringency_index**: takes values ranging from 0 to 100, which seems correct in the summary.
- **human_development_index**: takes values ranging from 0 to 1, which seems correnct in the summary.
- All other numerical/percentage values seem reasonable also.

In [22]:
df_selected_data_sorted.to_csv(r"C:\Users\Home1\Desktop\Rhoe Project\covid_data_cleaned3.csv", index = False)